#!/bin/sh
### BEGIN INIT INFO
# Provides:          telegram-alert
# Required-Start:    $network $remote_fs $syslog
# Required-Stop:     $network $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: TelegramAlert file monitor daemon
# Description:       Monitors a folder for recently modified files and sends
#                    Telegram alerts when matching files are found.
### END INIT INFO

# ----- Configuration --------------------------------------------------------
NAME="telegram-alert"
DAEMON="/usr/local/bin/telegram-alert"
CONFIG="/etc/telegram-alert/config.yml"
PIDFILE="/var/run/${NAME}.pid"
LOGFILE="/var/log/${NAME}.log"
DAEMON_USER="root"
# ----------------------------------------------------------------------------

. /lib/lsb/init-functions

do_start() {
    log_daemon_msg "Starting $NAME"

    if [ ! -x "$DAEMON" ]; then
        log_failure_msg "$DAEMON not found or not executable"
        return 1
    fi

    if [ ! -f "$CONFIG" ]; then
        log_failure_msg "Config file $CONFIG not found"
        return 1
    fi

    start-stop-daemon --start \
        --quiet \
        --make-pidfile \
        --pidfile "$PIDFILE" \
        --background \
        --chuid "$DAEMON_USER" \
        --startas /bin/sh \
        -- -c "exec $DAEMON -config $CONFIG >> $LOGFILE 2>&1"

    status=$?
    log_end_msg $status
    return $status
}

do_stop() {
    log_daemon_msg "Stopping $NAME"

    start-stop-daemon --stop \
        --quiet \
        --pidfile "$PIDFILE" \
        --retry=TERM/30/KILL/5

    status=$?
    rm -f "$PIDFILE"
    log_end_msg $status
    return $status
}

do_status() {
    status_of_proc -p "$PIDFILE" "$DAEMON" "$NAME"
}

case "$1" in
    start)
        do_start
        ;;
    stop)
        do_stop
        ;;
    restart|force-reload)
        do_stop
        do_start
        ;;
    status)
        do_status
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|force-reload|status}" >&2
        exit 1
        ;;
esac
